# Containerize a Web App with Docker Compose
# Source: https://docs.docker.com/compose/gettingstarted/
# Generated by BuildBridge

print("Starting: Containerize a Web App with Docker Compose")

# Step 1: Create the project directory and source files
